#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum
{
    LED_SERVICE,
    LED_RED_CHARACTERISTIC,
    LED_RED_CHARACTERISTIC_VALUE,
    LED_RED_CHARACTERISTIC_CONFIGURATION,

    LED_GREEN_CHARACTERISTIC,
    LED_GREEN_CHARACTERISTIC_VALUE,
    LED_GREEN_CHARACTERISTIC_CONFIGURATION,

    LED_BLUE_CHARACTERISTIC,
    LED_BLUE_CHARACTERISTIC_VALUE,
    LED_BLUE_CHARACTERISTIC_CONFIGURATION,

    LED_RGB_CHARACTERISTIC,
    LED_RGB_CHARACTERISTIC_VALUE,
    LED_RGB_CHARACTERISTIC_CONFIGURATION,

    LED_INDEX_NUMBER,
};